export const mockAnalysis = {
  predictedTime: 315,
  slow: true,
  slowProbability: 0.7823,
  confidence: "medium",
  predictionSource: "heuristic",
  suggestedIndex: "CREATE INDEX idx_users_status_total ON users(status, total);",
  suggestedIndexes: [
    "CREATE INDEX idx_users_status_total ON users(status, total);",
    "CREATE INDEX idx_users_status ON users(status);",
    "CREATE INDEX idx_users_total ON users(total);",
  ],
  optimizedQuery: "SELECT status, total FROM users u JOIN orders o ON u.id = o.user_id WHERE u.status = 'active' AND o.total > 100 ORDER BY o.created_at;",
  optimizationTips: [
    "Replace SELECT * with specific column names to reduce I/O and enable covering indexes.",
    "ORDER BY without LIMIT forces a full sort \u2014 add LIMIT if only top rows are needed.",
  ],
  queryFeatures: {
    tables: ["users", "orders"],
    joins: 1,
    conditions: 3,
    subqueries: 0,
    hasWildcard: true,
    hasOrderBy: true,
    hasGroupBy: false,
    hasHaving: false,
    hasDistinct: false,
    hasLimit: false,
    whereColumns: ["status", "total"],
    orderByColumns: ["created_at"],
    groupByColumns: [],
    queryType: "SELECT",
  },
};
